# Generated by Django 2.0 on 2018-04-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='twitter_id',
            field=models.CharField(default='DEF_STRING', max_length=200),
        ),
    ]
