# Generated by Django 2.0 on 2018-04-10 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_cloud_twitter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloud',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
